# Lab-Based Quiz 4  
# Time: 1 hour
## Comparing Individual Models vs Ensemble Methods  
### Dataset: Breast Cancer Wisconsin (Diagnostic)


## Objective

In this lab, you will:

1. Train and evaluate the following classifiers individually:
   - Decision Tree
   - Naive Bayes
   - K-Nearest Neighbors (KNN)
   - Logistic Regression
   - SGD Classifier

2. Build ensemble models using:
   - Hard Voting
   - Soft Voting
   - Bagging
   - Random Forest
   - AdaBoost

3. Compare all models using appropriate evaluation metrics.

4. Decide which metric best represents performance in this case study and justify your reasoning.

5. Write your own summary explaining your findings.

**Important**:
- Do NOT hard-code results.
- Do NOT use Gemini or any LLM model to do this for you.
- All answers must be written in your own words.
- Replace each TODO with working code.

# Part 1 – Load and Explore the Dataset

The Breast Cancer Wisconsin dataset is a binary classification dataset.

In [13]:
# TODO: Import necessary libraries
import pandas as pd
import numpy as np

# TODO: Load the breast cancer dataset from sklearn.datasets
from sklearn.datasets import load_breast_cancer
breast_cancer = load_breast_cancer()
# TODO: Convert the dataset to a pandas DataFrame (features + target)
data = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)
data['target'] = breast_cancer.target

# TODO: Display the first 5 rows of the dataset
display(data.head())

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

## Basic Exploration

1. How many samples and features are there?
  31 feautures, 569 samples
2. What are the target classes?
  Yes or no for breast cancer
3. Is the dataset balanced?
  No

In [9]:
# TODO: Print dataset shape
print("Dataset Shape:")
print(data.shape)
# TODO: Print class distribution
print("Class Distribution:")
print(data['target'].value_counts())
# TODO: Compute percentage of each class
print("Percentage of each class:")
print(data['target'].value_counts(normalize=True) * 100)

Dataset Shape:
(569, 31)
Class Distribution:
target
1    357
0    212
Name: count, dtype: int64
Percentage of each class:
target
1    62.741652
0    37.258348
Name: proportion, dtype: float64

### Write your answers below:

- Number of samples:
- Number of features:
- Class distribution:
- Is the dataset balanced?


There are 569 samples with 31 features including the target variable. The dataset is not balanced with about 63 percent having target variable 1 and about 37 percent with target variable 0.

# Part 2 – Train/Test Split and Scaling

In [14]:
# TODO: Perform train_test_split
from sklearn.model_selection import train_test_split
# - 80% training
# - 20% testing
# - random_state=42
X = data.drop('target', axis=1)
y = data['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
# TODO: Apply StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### In 2–3 sentences:
Why is scaling necessary for some models but not for others?

Some models are affected by the scale of the data, and others are not. Decision tree, for example, makes decisions within each feature, so the data does not need to be scaled. KNN would be thrown off by having unscaled data becasue it uses distance measurements between features.

# Part 3 – Train Individual Models

For EACH model:

* Train

* Predict

* Compute:

  * Accuracy

  * Precision

  * Recall

  * F1-score

  * Confusion Matrix

Store results for later comparison

In [36]:
# TODO: Import DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
# TODO: Initialize model
dt = DecisionTreeClassifier(random_state=42)
# TODO: Fit model
dt.fit(X_train, y_train)
# TODO: Predict
dt_pred = dt.predict(X_test)
# TODO: Compute evaluation metrics

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

cm = confusion_matrix(y_test, dt_pred)
print("Confusion Matrix:\n", cm)

accuracy = accuracy_score(y_test, dt_pred)
print(f"Accuracy: {accuracy:.2f}")

precision = precision_score(y_test, dt_pred)
print(f"Precision: {precision:.2f}")

recall = recall_score(y_test, dt_pred)
print(f"Recall: {recall:.2f}")

f1 = f1_score(y_test, dt_pred)
print(f"F1-Score: {f1:.2f}")

# TODO: Store results in a dictionary
dt_results = {
    'Model': 'Decision Tree',
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-score': f1
}

Confusion Matrix:
 [[40  3]
 [ 3 68]]
Accuracy: 0.95
Precision: 0.96
Recall: 0.96
F1-Score: 0.96

In [37]:
# TODO: Import GaussianNB
from sklearn.naive_bayes import GaussianNB
# TODO: Initialize model
GNB = GaussianNB()
# TODO: Fit model
GNB.fit(X_train, y_train)
# TODO: Predict
gnb_pred = GNB.predict(X_test)
# TODO: Compute evaluation metrics
cm = confusion_matrix(y_test, gnb_pred)
print("Confusion Matrix:\n", cm)

accuracy = accuracy_score(y_test, gnb_pred)
print(f"Accuracy: {accuracy:.2f}")

precision = precision_score(y_test, gnb_pred)
print(f"Precision: {precision:.2f}")

recall = recall_score(y_test, gnb_pred)
print(f"Recall: {recall:.2f}")

f1 = f1_score(y_test, gnb_pred)
print(f"F1-Score: {f1:.2f}")
# TODO: Store results
gnb_results = {
    'Model': 'Naive Bayes',
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-score': f1
}

Confusion Matrix:
 [[40  3]
 [ 1 70]]
Accuracy: 0.96
Precision: 0.96
Recall: 0.99
F1-Score: 0.97

In [38]:
# TODO: Import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
# TODO: Initialize model
knn = KNeighborsClassifier()
# TODO: Fit model
knn.fit(X_train, y_train)
# TODO: Predict
knn_pred = knn.predict(X_test)
# TODO: Compute evaluation metrics
cm = confusion_matrix(y_test, knn_pred)
print("Confusion Matrix:\n", cm)

accuracy = accuracy_score(y_test, knn_pred)
print(f"Accuracy: {accuracy:.2f}")

precision = precision_score(y_test, knn_pred)
print(f"Precision: {precision:.2f}")

recall = recall_score(y_test, knn_pred)
print(f"Recall: {recall:.2f}")

f1 = f1_score(y_test, knn_pred)
print(f"F1-Score: {f1:.2f}")
# TODO: Store results
knn_results = {
    'Model': 'K-Nearest Neighbors',
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-score': f1
}

Confusion Matrix:
 [[40  3]
 [ 3 68]]
Accuracy: 0.95
Precision: 0.96
Recall: 0.96
F1-Score: 0.96

In [39]:
# TODO: Import LogisticRegression
from sklearn.linear_model import LogisticRegression
# TODO: Initialize model
log_reg = LogisticRegression(random_state=42)
# TODO: Fit model
log_reg.fit(X_train, y_train)
# TODO: Predict
log_reg_pred = log_reg.predict(X_test)
# TODO: Compute evaluation metrics
cm = confusion_matrix(y_test, log_reg_pred)
print("Confusion Matrix:\n", cm)

accuracy = accuracy_score(y_test, log_reg_pred)
print(f"Accuracy: {accuracy:.2f}")

precision = precision_score(y_test, log_reg_pred)
print(f"Precision: {precision:.2f}")

recall = recall_score(y_test, log_reg_pred)
print(f"Recall: {recall:.2f}")

f1 = f1_score(y_test, log_reg_pred)
print(f"F1-Score: {f1:.2f}")
# TODO: Store results
log_reg_results = {
    'Model': 'Logistic Regression',
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-score': f1
}

Confusion Matrix:
 [[41  2]
 [ 1 70]]
Accuracy: 0.97
Precision: 0.97
Recall: 0.99
F1-Score: 0.98

In [40]:
# TODO: Import SGDClassifier
from sklearn.linear_model import SGDClassifier
# TODO: Initialize model
sgd = SGDClassifier(random_state=42)
# TODO: Fit model
sgd.fit(X_train, y_train)
# TODO: Predict
sgd_pred = sgd.predict(X_test)
# TODO: Compute evaluation metrics
cm = confusion_matrix(y_test, sgd_pred)
print("Confusion Matrix:\n", cm)

accuracy = accuracy_score(y_test, sgd_pred)
print(f"Accuracy: {accuracy:.2f}")

precision = precision_score(y_test, sgd_pred)
print(f"Precision: {precision:.2f}")

recall = recall_score(y_test, sgd_pred)
print(f"Recall: {recall:.2f}")

f1 = f1_score(y_test, sgd_pred)
print(f"F1-Score: {f1:.2f}")
# TODO: Store results
sgd_results = {
    'Model': 'SGD Classifier',
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-score': f1
}

Confusion Matrix:
 [[42  1]
 [ 3 68]]
Accuracy: 0.96
Precision: 0.99
Recall: 0.96
F1-Score: 0.97

# Part 4 – Voting Classifier

In [41]:
# TODO: Import VotingClassifier
from sklearn.ensemble import VotingClassifier
# TODO: Create hard voting classifier using at least 3 base models
estimators = [
    ('decision_tree', dt),
    ('knn', knn),
    ('log_reg', log_reg),
]

# TODO: Fit model
voting_clf = VotingClassifier(estimators=estimators, voting='hard', n_jobs=-1)
voting_clf.fit(X_train, y_train)
# TODO: Predict
voting_pred = voting_clf.predict(X_test)
# TODO: Compute evaluation metrics
cm = confusion_matrix(y_test, voting_pred)
print("Confusion Matrix:\n", cm)

accuracy = accuracy_score(y_test, voting_pred)
print(f"Accuracy: {accuracy:.2f}")

precision = precision_score(y_test, voting_pred)
print(f"Precision: {precision:.2f}")

recall = recall_score(y_test, voting_pred)
print(f"Recall: {recall:.2f}")

f1 = f1_score(y_test, voting_pred)
print(f"F1-Score: {f1:.2f}")
# TODO: Store results
hard_voting_results = {
    'Model': 'Hard Voting',
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-score': f1
}

Confusion Matrix:
 [[41  2]
 [ 1 70]]
Accuracy: 0.97
Precision: 0.97
Recall: 0.99
F1-Score: 0.98

In [42]:
# TODO: Create soft voting classifier
soft_voting_clf = VotingClassifier(estimators=estimators, voting='soft', n_jobs=-1)
# TODO: Fit model
soft_voting_clf.fit(X_train, y_train)
# TODO: Predict
soft_voting_pred = soft_voting_clf.predict(X_test)
# TODO: Compute evaluation metrics
cm = confusion_matrix(y_test, soft_voting_pred)
print("Confusion Matrix:\n", cm)

accuracy = accuracy_score(y_test, soft_voting_pred)
print(f"Accuracy: {accuracy:.2f}")

precision = precision_score(y_test, soft_voting_pred)
print(f"Precision: {precision:.2f}")

recall = recall_score(y_test, soft_voting_pred)
print(f"Recall: {recall:.2f}")

f1 = f1_score(y_test, soft_voting_pred)
print(f"F1-Score: {f1:.2f}")
# TODO: Store results
soft_voting_results = {
    'Model': 'Soft Voting',
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-score': f1
}

Confusion Matrix:
 [[41  2]
 [ 1 70]]
Accuracy: 0.97
Precision: 0.97
Recall: 0.99
F1-Score: 0.98

### In 2–3 sentences:
What is the difference between hard voting and soft voting?

# Part 5 – Bagging and Boosting

In [43]:
# TODO: Import BaggingClassifier
from sklearn.ensemble import BaggingClassifier
# TODO: Initialize Bagging model (choose base estimator)
bagging_clf = BaggingClassifier(estimator=dt, n_estimators=10, random_state=42)
# TODO: Fit model
bagging_clf.fit(X_train, y_train)
# TODO: Predict
bagging_pred = bagging_clf.predict(X_test)
# TODO: Compute evaluation metrics
cm = confusion_matrix(y_test, bagging_pred)
print("Confusion Matrix:\n", cm)

accuracy = accuracy_score(y_test, bagging_pred)
print(f"Accuracy: {accuracy:.2f}")

precision = precision_score(y_test, bagging_pred)
print(f"Precision: {precision:.2f}")

recall = recall_score(y_test, bagging_pred)
print(f"Recall: {recall:.2f}")

f1 = f1_score(y_test, bagging_pred)
print(f"F1-Score: {f1:.2f}")
# TODO: Store results
bagging_results = {
    'Model': 'Bagging',
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-score': f1
}

Confusion Matrix:
 [[40  3]
 [ 2 69]]
Accuracy: 0.96
Precision: 0.96
Recall: 0.97
F1-Score: 0.97

In [44]:
# TODO: Import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

# TODO: Initialize model
rf_clf = RandomForestClassifier(random_state=42)

# TODO: Fit model
rf_clf.fit(X_train, y_train)

# TODO: Predict
rf_pred = rf_clf.predict(X_test)

# TODO: Compute evaluation metrics
cm = confusion_matrix(y_test, rf_pred)
print("Confusion Matrix:\n", cm)

accuracy = accuracy_score(y_test, rf_pred)
print(f"Accuracy: {accuracy:.2f}")

precision = precision_score(y_test, rf_pred)
print(f"Precision: {precision:.2f}")

recall = recall_score(y_test, rf_pred)
print(f"Recall: {recall:.2f}")

f1 = f1_score(y_test, rf_pred)
print(f"F1-Score: {f1:.2f}")

# TODO: Store results
rf_results = {
    'Model': 'Random Forest',
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-score': f1
}

Confusion Matrix:
 [[40  3]
 [ 1 70]]
Accuracy: 0.96
Precision: 0.96
Recall: 0.99
F1-Score: 0.97

In [45]:
# TODO: Import AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier

# TODO: Initialize model
adaboost_clf = AdaBoostClassifier(estimator=dt, n_estimators=100, random_state=42)

# TODO: Fit model
adaboost_clf.fit(X_train, y_train)

# TODO: Predict
adaboost_pred = adaboost_clf.predict(X_test)

# TODO: Compute evaluation metrics
cm = confusion_matrix(y_test, adaboost_pred)
print("Confusion Matrix:\n", cm)

accuracy = accuracy_score(y_test, adaboost_pred)
print(f"Accuracy: {accuracy:.2f}")

precision = precision_score(y_test, adaboost_pred)
print(f"Precision: {precision:.2f}")

recall = recall_score(y_test, adaboost_pred)
print(f"Recall: {recall:.2f}")

f1 = f1_score(y_test, adaboost_pred)
print(f"F1-Score: {f1:.2f}")

# TODO: Store results
adaboost_results = {
    'Model': 'AdaBoost',
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-score': f1
}

Confusion Matrix:
 [[39  4]
 [ 3 68]]
Accuracy: 0.94
Precision: 0.94
Recall: 0.96
F1-Score: 0.95

# Part 6 – Model Comparison

In [46]:
# TODO: Create a comparison DataFrame that includes:

# Model Name
# Accuracy
# Precision
# Recall
# F1-score
all_results = [
    dt_results,
    gnb_results,
    knn_results,
    log_reg_results,
    sgd_results,
    hard_voting_results,
    soft_voting_results,
    bagging_results,
    rf_results,
    adaboost_results
]

comparison_df = pd.DataFrame(all_results)

# TODO: Sort results by F1-score (descending)
comparison_df = comparison_df.sort_values(by='F1-score', ascending=False)

# TODO: Display the table
display(comparison_df)

                 Model  Accuracy  Precision    Recall  F1-score
5          Hard Voting  0.973684   0.972222  0.985915  0.979021
3  Logistic Regression  0.973684   0.972222  0.985915  0.979021
6          Soft Voting  0.973684   0.972222  0.985915  0.979021
1          Naive Bayes  0.964912   0.958904  0.985915  0.972222
8        Random Forest  0.964912   0.958904  0.985915  0.972222
4       SGD Classifier  0.964912   0.985507  0.957746  0.971429
7              Bagging  0.956140   0.958333  0.971831  0.965035
0        Decision Tree  0.947368   0.957746  0.957746  0.957746
2  K-Nearest Neighbors  0.947368   0.957746  0.957746  0.957746
9             AdaBoost  0.938596   0.944444  0.957746  0.951049

# Part 7 – Metric Selection and Interpretation

Answer the following:

1. Which model achieved the highest accuracy?
The ensemble voting classifiers and logistic regression tied with the highest accuracy.
2. Which model achieved the highest recall?
Hard voting, soft voting, logistic regression, naive bayes, and random forest all had the same recall, higher than the other models.
3. Which model achieved the highest F1-score?
Hard voting, soft voting, and logistic regression tied for the highest F1-Score.
4. In the context of breast cancer diagnosis:
   - Which metric is most important?
    I would say that recall is the most important
   - Why?
   You want to identify as many positives as possible and not miss any positives. You do not want false negatives. A false positive is also bad, but not as bad, especially if more testing is possible. It is most important to detect all cases of cancer.
5. If a model has high accuracy but low recall, what does that imply in this medical context?
    Low recall means that it is not detecting all positive cases. With high accuracy and low recall, it is good at detecting all negatives correctly, but misses some positives.

# Part 8 – Final Reflection (Required)

## Final Reflection (1-2 paragraphs)

Write a short summary in your own words explaining:

- What you observed when comparing individual models vs ensemble models.
- Whether ensemble methods improved performance.
- Which model you would choose for real-world deployment.
- Which metric best represents performance in this case study and why.
- Any surprising findings.


### Your Reflection:

Ensemble methods were the best performing and are what I would most likely choose for real world deployment. This was done quickly without hyperparameter tuning and it would have been interesting to see if the ensemble methods could have performed better with other models used as the estimators.
For cancer detection, recall is the most important, and F1 score is also a good metric since it reflects presision and recall. The main thing that you want is to detect as many positive cases as possible, while also secondarily minimizing the false positives.

I was surprised that all of the models had pretty high performance, I would be interested if it could be improved.